server:
    port: 8091
    servlet:
        encoding:
            charset: UTF-8
            force: true
            enabled: true

spring:
    application:
        name: mcp
    main:
        banner-mode: off
        web-application-type: none
        allow-bean-definition-overriding: true
    ai:
        mcp:
            server:
                name: ${spring.application.name}
                version: 1.0.0

app:
    download:
        path: C:/Users/29525/MyResources
        base: https://www.bidutuijian.com

#logging:
#    pattern:
#        console:
#    file:
#        name: data/log/${spring.application.name}.log


